# Generated by Django 3.0.8 on 2020-07-07 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='first_name')),
                ('middle_names', models.CharField(max_length=120, null=True, verbose_name='middle_names')),
                ('last_name', models.CharField(max_length=120, null=True, verbose_name='last_name')),
                ('born', models.DateField()),
                ('died', models.DateField(null=True)),
                ('father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_father', to='geneal.Person')),
                ('mother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_mother', to='geneal.Person')),
            ],
        ),
    ]
